name: CI (Monorepo)

on:
  push:

# ---- set your ACR name once here ----
env:
  ACR_NAME: lucasacr9c
  REGISTRY_FQDN: ${{ env.ACR_NAME }}.azurecr.io
  IMAGE_TAG: ${{ github.sha }}   # unique tag per commit; use "latest" if you prefer

jobs:
  test_and_lint_backends:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # keep whatever tests/linters you already had here
      - run: echo "✅ tests/linters go here (left unchanged)"

  build_and_push_images:
    runs-on: ubuntu-latest
    needs: test_and_lint_backends
    steps:
      - uses: actions/checkout@v4

      - name: Azure login (SP)
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: az acr login --name "${{ env.ACR_NAME }}"

      - name: Build & push Product Service
        run: |
          docker build -t "${REGISTRY_FQDN}/product_service:${IMAGE_TAG}" ./product_service/
          docker push    "${REGISTRY_FQDN}/product_service:${IMAGE_TAG}"

      - name: Build & push Order Service
        run: |
          docker build -t "${REGISTRY_FQDN}/order_service:${IMAGE_TAG}" ./order_service/
          docker push    "${REGISTRY_FQDN}/order_service:${IMAGE_TAG}"

  build_and_push_frontend:
    runs-on: ubuntu-latest
    needs: test_and_lint_backends
    steps:
      - uses: actions/checkout@v4

      - name: Azure login (SP)
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: az acr login --name "${{ env.ACR_NAME }}"

      - name: Build & push Frontend
        run: |
          docker build -t "${REGISTRY_FQDN}/frontend:${IMAGE_TAG}" ./frontend/
          docker push    "${REGISTRY_FQDN}/frontend:${IMAGE_TAG}"